
#ifndef SYSTM_DATABASEDEFINES
#define SYSTM_DATABASEDEFINES

#define SYSTM_DB_INT 			1
#define SYSTM_DB_SHORT 		2
#define SYSTM_DB_FLOAT 		3
#define SYSTM_DB_DOUBLE 		4
#define SYSTM_DB_STRING 		5


#endif
